server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./h2db
    username: sa
    password:


  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  #spring:
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/testcontainer?serverTimezone=Asia/SeoulZ
  #    username: root
  #    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true  # Hibernate가 생성하는 SQL을 로그로 출력


  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

logging:
  level:
    root: info

#
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    path: /swagger/index.html
#    groups-order: DESC
#    doc-expansion: none
#    tags-sorter: alpha
#    operationsSorter: method
#    disable-swagger-default-url: true
#    display-request-duration: true

upload:
  directory: C:\otherGitClone








